class MetadataConstants:
    CLUSTER_ID = "cluster_id"
    TOPICS = "topics"
    NUM_BROKERS = "num_brokers"
    NUM_PARTITIONS = "num_partitions"
    CLEANUP_POLICY = "cleanup_policy"
    TOPIC_NAME = "name"
    RETENTION_TIME = "retention_time"
    RETENTION_SPACE = "retention_space"
    MIN_COMPACTION_LAG = "min_compaction_lag"
    MAX_COMPACTION_LAG = "max_compaction_lag"
    BOOTSTRAP_SERVER = "bootstrap_server"
